### ISSUE TITLE
What is the end to end experience?

### ISSUE THREAD

**Issue by danielreed** [HewlettPackard/hpe-oneview-hubot#7]
A general, relational experience with the bot can help express the interactive character of the user's experience. It should be one that is comfortable, trustworthy, and gives the user the desire/confidence to return.

Consider a collaborative meeting with an integrated team member or friend:

1. Greeting - "Hello!"
2. Welcome request to accomplish a task - "What can I help you do today?"
3. Request is made - "I need to find out what SH is bad"
4. Response - "Let me go take a look and I'll be right back"
5. Any qualifying statements - "That's a pretty big lift, this might take a little while" or "Sure, one sec..."
6. Task Accomplished - "Here's what I found."
7. Opportunity to serve beyond original task - "What else can I help you with?" or something conditional, "Let me know if this is what you were looking for. Can I help you with anything else?"
8. End of conversation - "It's been great talking with you, see you next time."

**Comment by gregfuruiye** [comment]
It would be important to consider what kinds of ways in which users are going to ask questions. I'm not sure anyone is going to write out a questions, but rather, make statements and the bot can respond.

For example, the user should be able to input "hw". The bot could respond, "It looks like you want information about hardware. Could you be a bit more specific about what you're looking for?" Input: "bad hw" Reponse, "Ok, I found 24 servers with errors, would you like me to list them all, or just some of them?" Input: "All" Response: "Sure, here's what I found" and then list all HW in an error state.

**Comment by gregfuruiye** [comment]
@danielreed, I'm wondering if we need a "concluding" experience at all. It would be difficult to know when the user is done. With that in mind, I'd suggest staying focused on the requested tasks rather than trying to figure out if the user is done.

Request: bad hw
Response: Hold on a sec while I go check on any critical errors...
Response: It looks there are a few issues, here's what I found...

That's it because we don't really know what the user wants to do next or what the errors contain, correct?
